### ISSUE TITLE
Decide on the tech stack

### ISSUE THREAD

**Issue by the-dagger** [JBossOutreach/certificate-generator-server#1]
Decide to go ahead with the current stack or move on to a different tech stack.
cc : @aashutoshrathi @vibhor98 @jatinkatyal13 @theexplorist

**Comment by jatinkatyal13** [comment]
The current stack is perfect for this application in my opinion and also beginner friendly for the participants !

**Comment by jatinkatyal13** [comment]
@the-dagger should I migrate the codebase to Django application and create a README ?

**Comment by theexplorist** [comment]
So django is decided for backend?

**Comment by aashutoshrathi** [comment]
@theexplorist Probably.
@jatinkatyal13 Django works for me too.

**Comment by the-dagger** [comment]
Also, you should have received write access to all the GCI repos.
Regardless, it's a good idea to create pull requests unless you are doing a very minor change.

**Comment by jatinkatyal13** [comment]
@the-dagger sure !

**Comment by the-dagger** [comment]
Ok, moving ahead with Django then.
Please move on to #2
