### ISSUE TITLE
README.md requires changes

### ISSUE THREAD

**Issue by neeraj3029** [JBossOutreach/certificate-generator-server#4]
README.md requires the following updates:

1. Step to activate the virtual environment is missing.
2. The command which is presently provided to create virtual environment will create one using the Python installed in the system, which is always Python 2.7 in MacOS.

**Comment by jatinkatyal13** [comment]
@neeraj3029 for installing virtualenv let's stick with installing the dependencies with pip. May be we can add runtime.txt so the user would know which python version to use ! Also we can use virtualenv's -p flag to explicitly specify the python version.
