### ISSUE TITLE
Travis CI implementation

### ISSUE THREAD

**Issue by TITANMQ** [JBossOutreach/certificate-generator-server#41]
I would like to implement Travis CI, a hosted service which builds and tests projects on Github.

**Comment by jatinkatyal13** [comment]
That would be awesome! 🎉 
We want our tests to try to make migrations, migrate them and run the tests that we have made!
For reference you can checkout [this](https://github.com/aashutoshrathi/labper/blob/master/.travis.yml)

All the best 👍

**Comment by TITANMQ** [comment]
Okay great thanks! 👍
