### ISSUE TITLE
Write a depoloy script

### ISSUE THREAD

**Issue by jatinkatyal13** [JBossOutreach/certificate-generator-server#9]
Create a python script the automatically deploys the application to heroku. You can use argparse library to create some command line arguments for the script like branch to deploy, heroku app name etc.

Learn more about heroku [here](https://devcenter.heroku.com/start)

**Comment by aashutoshrathi** [comment]
No need of a script @jatinkatyal13 Share Heroku App with me, I'll set up with that with sample tests.

**Comment by aashutoshrathi** [comment]
Closing this for now. :wink:
